// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8LeP7YWe9_mQgSXUSgD7Y-ZfbQDQkzlI',
    appId: '1:1081914513944:web:8973c351f6dd51258d816d',
    messagingSenderId: '1081914513944',
    projectId: 'notes-afe15',
    authDomain: 'notes-afe15.firebaseapp.com',
    storageBucket: 'notes-afe15.appspot.com',
    measurementId: 'G-L2MTFM97VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo7SMuHIP78AN_42iN8LJ76gH2UeNfzQI',
    appId: '1:1081914513944:android:3b00182f5b4688ad8d816d',
    messagingSenderId: '1081914513944',
    projectId: 'notes-afe15',
    storageBucket: 'notes-afe15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vekCT3f4i3NK_Is6vGT2S2dgg8PbD6k',
    appId: '1:1081914513944:ios:7baae65353105a778d816d',
    messagingSenderId: '1081914513944',
    projectId: 'notes-afe15',
    storageBucket: 'notes-afe15.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-vekCT3f4i3NK_Is6vGT2S2dgg8PbD6k',
    appId: '1:1081914513944:ios:7baae65353105a778d816d',
    messagingSenderId: '1081914513944',
    projectId: 'notes-afe15',
    storageBucket: 'notes-afe15.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8LeP7YWe9_mQgSXUSgD7Y-ZfbQDQkzlI',
    appId: '1:1081914513944:web:4487abcf565b75308d816d',
    messagingSenderId: '1081914513944',
    projectId: 'notes-afe15',
    authDomain: 'notes-afe15.firebaseapp.com',
    storageBucket: 'notes-afe15.appspot.com',
    measurementId: 'G-TVZRYT0E3P',
  );
}
